// flow-typed signature: 3adf963287d46cf4a7f824e1af626e9c
// flow-typed version: <<STUB>>/@types/jest_v^29.5.13/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/jest' {
  declare module.exports: any;
}
