// flow-typed signature: 542504df021cf2734b71e5fa420b13c6
// flow-typed version: <<STUB>>/glob_v^11.0.0/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'glob'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'glob' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'glob/dist/commonjs/glob' {
  declare module.exports: any;
}

declare module 'glob/dist/commonjs/has-magic' {
  declare module.exports: any;
}

declare module 'glob/dist/commonjs/ignore' {
  declare module.exports: any;
}

declare module 'glob/dist/commonjs' {
  declare module.exports: any;
}

declare module 'glob/dist/commonjs/pattern' {
  declare module.exports: any;
}

declare module 'glob/dist/commonjs/processor' {
  declare module.exports: any;
}

declare module 'glob/dist/commonjs/walker' {
  declare module.exports: any;
}

declare module 'glob/dist/esm/glob' {
  declare module.exports: any;
}

declare module 'glob/dist/esm/has-magic' {
  declare module.exports: any;
}

declare module 'glob/dist/esm/ignore' {
  declare module.exports: any;
}

declare module 'glob/dist/esm' {
  declare module.exports: any;
}

declare module 'glob/dist/esm/pattern' {
  declare module.exports: any;
}

declare module 'glob/dist/esm/processor' {
  declare module.exports: any;
}

declare module 'glob/dist/esm/walker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'glob/dist/commonjs/glob.js' {
  declare module.exports: $Exports<'glob/dist/commonjs/glob'>;
}
declare module 'glob/dist/commonjs/has-magic.js' {
  declare module.exports: $Exports<'glob/dist/commonjs/has-magic'>;
}
declare module 'glob/dist/commonjs/ignore.js' {
  declare module.exports: $Exports<'glob/dist/commonjs/ignore'>;
}
declare module 'glob/dist/commonjs/index' {
  declare module.exports: $Exports<'glob/dist/commonjs'>;
}
declare module 'glob/dist/commonjs/index.js' {
  declare module.exports: $Exports<'glob/dist/commonjs'>;
}
declare module 'glob/dist/commonjs/pattern.js' {
  declare module.exports: $Exports<'glob/dist/commonjs/pattern'>;
}
declare module 'glob/dist/commonjs/processor.js' {
  declare module.exports: $Exports<'glob/dist/commonjs/processor'>;
}
declare module 'glob/dist/commonjs/walker.js' {
  declare module.exports: $Exports<'glob/dist/commonjs/walker'>;
}
declare module 'glob/dist/esm/glob.js' {
  declare module.exports: $Exports<'glob/dist/esm/glob'>;
}
declare module 'glob/dist/esm/has-magic.js' {
  declare module.exports: $Exports<'glob/dist/esm/has-magic'>;
}
declare module 'glob/dist/esm/ignore.js' {
  declare module.exports: $Exports<'glob/dist/esm/ignore'>;
}
declare module 'glob/dist/esm/index' {
  declare module.exports: $Exports<'glob/dist/esm'>;
}
declare module 'glob/dist/esm/index.js' {
  declare module.exports: $Exports<'glob/dist/esm'>;
}
declare module 'glob/dist/esm/pattern.js' {
  declare module.exports: $Exports<'glob/dist/esm/pattern'>;
}
declare module 'glob/dist/esm/processor.js' {
  declare module.exports: $Exports<'glob/dist/esm/processor'>;
}
declare module 'glob/dist/esm/walker.js' {
  declare module.exports: $Exports<'glob/dist/esm/walker'>;
}
