// flow-typed signature: 7d82b6e9cd8ba474598acb8188b32183
// flow-typed version: <<STUB>>/postcss-preset-env_v^10.0.7/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-preset-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-preset-env' {
  declare module.exports: any;
}
