// flow-typed signature: 14bbfc9d176f8e72260db75a3db5ddba
// flow-typed version: <<STUB>>/rollup-plugin-postcss_v^4.0.2/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-postcss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-postcss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-postcss/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-postcss/dist/index' {
  declare module.exports: $Exports<'rollup-plugin-postcss/dist'>;
}
declare module 'rollup-plugin-postcss/dist/index.js' {
  declare module.exports: $Exports<'rollup-plugin-postcss/dist'>;
}
