// flow-typed signature: 4c90663828cd81c7b3a3ad0a64cbe580
// flow-typed version: <<STUB>>/@arpitmalik832/react-js-rollup-library_vlink:/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@arpitmalik832/react-js-rollup-library'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@arpitmalik832/react-js-rollup-library' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@arpitmalik832/react-js-rollup-library/build_utils/scripts/generate_icons_list' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/build_utils/scripts/minify_dts' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/build_utils/scripts/updateImportForMixins' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/dist/cjs/assets/icons/lg32/standardAccount.svg' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/dist/cjs/assets/icons/rg24/systemActionABCKeypad.svg' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/dist/cjs/assets/icons/sm16/systemAdd.svg' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/dist/cjs/lib' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/dist/esm/assets/icons/lg32/standardAccount.svg' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/dist/esm/assets/icons/rg24/systemActionABCKeypad.svg' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/dist/esm/assets/icons/sm16/systemAdd.svg' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/dist/esm/lib' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/eslint.config' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/flow-typed/dependencies' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/flow-typed/npm/axios_v1.x.x' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/flow-typed/npm/express_v4.x.x' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/flow-typed/npm/jest_v29.x.x' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/flow-typed/npm/lodash_v4.x.x' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/flow-typed/npm/rxjs_v7.x.x' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/flow-typed/npm/string-natural-compare_v3.x.x' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/flow-typed/npm/webpack_v5.x.x' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/flow-typed/npm/webpack-bundle-analyzer_v4.x.x' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/flow-typed/types' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/jest.config' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/jest.setup' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/knip.config' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/rollup.config' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/scripts/colors_css_to_mdx' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/scripts/colors_scss_to_mdx' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/scripts/serve_storybook' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/scripts/typography_scss_to_mdx' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/__tests__/__mocks__/assetMock' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/__tests__/__mocks__/fetchMock' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/__tests__/__mocks__/matchMediaMock' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/__tests__/__mocks__/svgrMock' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/components/__tests__/index.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/components/atoms/__tests__/Button.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/components/atoms/__tests__/ComponentWithSuspense.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/components/atoms/__tests__/HtmlContent.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/components/atoms/__tests__/index.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/components/atoms/Button' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/components/atoms/Button/index.stories' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/components/atoms/ComponentWithSuspense' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/components/atoms/HtmlContent' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/components/atoms' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/components' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/components/organisms/__tests__/index.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/components/organisms/__tests__/Loader.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/components/organisms' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/components/organisms/Loader' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/enums/app' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/enums' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/enums/redux' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/enums/sw' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/hooks/__tests__/useApiRequest.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/hooks/__tests__/useBackPress.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/hooks/__tests__/useTheme.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/hooks' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/hooks/useApiRequest' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/hooks/useBackPress' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/hooks/useTheme' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/providers/__tests__/ReduxProvider.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/providers' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/providers/ReduxProvider' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/redux' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/redux/queries/__tests__/baseQueryFn.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/redux/queries/baseQueryFn' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/redux/queries' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/redux/slices/__tests__/apisSlice.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/redux/slices/__tests__/appSlice.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/redux/slices/__tests__/navigationSlice.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/redux/slices/apisSlice' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/redux/slices/appSlice' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/redux/slices' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/redux/slices/navigationSlice' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/services/__tests__/SWRegistration.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/services' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/services/SWRegistration' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/stories/__tests__/Colors.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/stories/__tests__/Icons.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/stories/__tests__/Typography.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/stories/Colors' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/stories/Colors/index.stories' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/stories/Icons' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/stories/Icons/index.stories' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/stories/Typography' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/stories/Typography/index.stories' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/apiUtils.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/appUtils.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/arrayUtils.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/beforeUnload.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/classNames.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/commonUtils.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/converters.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/cookieUtils.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/deviceUtils.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/load.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/logsUtils.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/objectUtils.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/preferredColorScheme.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/queryUtils.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/reactUtils.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/reportWebVitals.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/stringUtils.test' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/apiUtils' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/appUtils' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/arrayUtils' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/classNames' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/commonUtils' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/converters' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/cookieUtils' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/deviceUtils' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/eventListeners/beforeUnload' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/eventListeners' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/eventListeners/load' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/eventListeners/preferredColorScheme' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/logsUtils' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/objectUtils' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/queryUtils' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/reactUtils' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/reportWebVitals' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/src/utils/stringUtils' {
  declare module.exports: any;
}

declare module '@arpitmalik832/react-js-rollup-library/style-dictionary.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@arpitmalik832/react-js-rollup-library/build_utils/scripts/generate_icons_list.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/build_utils/scripts/generate_icons_list'>;
}
declare module '@arpitmalik832/react-js-rollup-library/build_utils/scripts/minify_dts.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/build_utils/scripts/minify_dts'>;
}
declare module '@arpitmalik832/react-js-rollup-library/build_utils/scripts/updateImportForMixins.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/build_utils/scripts/updateImportForMixins'>;
}
declare module '@arpitmalik832/react-js-rollup-library/dist/cjs/assets/icons/lg32/standardAccount.svg.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/dist/cjs/assets/icons/lg32/standardAccount.svg'>;
}
declare module '@arpitmalik832/react-js-rollup-library/dist/cjs/assets/icons/rg24/systemActionABCKeypad.svg.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/dist/cjs/assets/icons/rg24/systemActionABCKeypad.svg'>;
}
declare module '@arpitmalik832/react-js-rollup-library/dist/cjs/assets/icons/sm16/systemAdd.svg.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/dist/cjs/assets/icons/sm16/systemAdd.svg'>;
}
declare module '@arpitmalik832/react-js-rollup-library/dist/cjs/lib.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/dist/cjs/lib'>;
}
declare module '@arpitmalik832/react-js-rollup-library/dist/esm/assets/icons/lg32/standardAccount.svg.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/dist/esm/assets/icons/lg32/standardAccount.svg'>;
}
declare module '@arpitmalik832/react-js-rollup-library/dist/esm/assets/icons/rg24/systemActionABCKeypad.svg.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/dist/esm/assets/icons/rg24/systemActionABCKeypad.svg'>;
}
declare module '@arpitmalik832/react-js-rollup-library/dist/esm/assets/icons/sm16/systemAdd.svg.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/dist/esm/assets/icons/sm16/systemAdd.svg'>;
}
declare module '@arpitmalik832/react-js-rollup-library/dist/esm/lib.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/dist/esm/lib'>;
}
declare module '@arpitmalik832/react-js-rollup-library/eslint.config.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/eslint.config'>;
}
declare module '@arpitmalik832/react-js-rollup-library/flow-typed/dependencies.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/flow-typed/dependencies'>;
}
declare module '@arpitmalik832/react-js-rollup-library/flow-typed/npm/axios_v1.x.x.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/flow-typed/npm/axios_v1.x.x'>;
}
declare module '@arpitmalik832/react-js-rollup-library/flow-typed/npm/express_v4.x.x.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/flow-typed/npm/express_v4.x.x'>;
}
declare module '@arpitmalik832/react-js-rollup-library/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@arpitmalik832/react-js-rollup-library/flow-typed/npm/jest_v29.x.x.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/flow-typed/npm/jest_v29.x.x'>;
}
declare module '@arpitmalik832/react-js-rollup-library/flow-typed/npm/lodash_v4.x.x.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/flow-typed/npm/lodash_v4.x.x'>;
}
declare module '@arpitmalik832/react-js-rollup-library/flow-typed/npm/rxjs_v7.x.x.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/flow-typed/npm/rxjs_v7.x.x'>;
}
declare module '@arpitmalik832/react-js-rollup-library/flow-typed/npm/string-natural-compare_v3.x.x.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/flow-typed/npm/string-natural-compare_v3.x.x'>;
}
declare module '@arpitmalik832/react-js-rollup-library/flow-typed/npm/webpack_v5.x.x.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/flow-typed/npm/webpack_v5.x.x'>;
}
declare module '@arpitmalik832/react-js-rollup-library/flow-typed/npm/webpack-bundle-analyzer_v4.x.x.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/flow-typed/npm/webpack-bundle-analyzer_v4.x.x'>;
}
declare module '@arpitmalik832/react-js-rollup-library/flow-typed/types.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/flow-typed/types'>;
}
declare module '@arpitmalik832/react-js-rollup-library/jest.config.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/jest.config'>;
}
declare module '@arpitmalik832/react-js-rollup-library/jest.setup.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/jest.setup'>;
}
declare module '@arpitmalik832/react-js-rollup-library/knip.config.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/knip.config'>;
}
declare module '@arpitmalik832/react-js-rollup-library/rollup.config.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/rollup.config'>;
}
declare module '@arpitmalik832/react-js-rollup-library/scripts/colors_css_to_mdx.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/scripts/colors_css_to_mdx'>;
}
declare module '@arpitmalik832/react-js-rollup-library/scripts/colors_scss_to_mdx.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/scripts/colors_scss_to_mdx'>;
}
declare module '@arpitmalik832/react-js-rollup-library/scripts/serve_storybook.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/scripts/serve_storybook'>;
}
declare module '@arpitmalik832/react-js-rollup-library/scripts/typography_scss_to_mdx.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/scripts/typography_scss_to_mdx'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/__tests__/__mocks__/assetMock.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/__tests__/__mocks__/assetMock'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/__tests__/__mocks__/fetchMock.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/__tests__/__mocks__/fetchMock'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/__tests__/__mocks__/matchMediaMock.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/__tests__/__mocks__/matchMediaMock'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/__tests__/__mocks__/svgrMock.jsx' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/__tests__/__mocks__/svgrMock'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/components/__tests__/index.test.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/components/__tests__/index.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/components/atoms/__tests__/Button.test.jsx' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/components/atoms/__tests__/Button.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/components/atoms/__tests__/ComponentWithSuspense.test.jsx' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/components/atoms/__tests__/ComponentWithSuspense.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/components/atoms/__tests__/HtmlContent.test.jsx' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/components/atoms/__tests__/HtmlContent.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/components/atoms/__tests__/index.test.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/components/atoms/__tests__/index.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/components/atoms/Button/index' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/components/atoms/Button'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/components/atoms/Button/index.jsx' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/components/atoms/Button'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/components/atoms/Button/index.stories.jsx' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/components/atoms/Button/index.stories'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/components/atoms/ComponentWithSuspense/index' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/components/atoms/ComponentWithSuspense'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/components/atoms/ComponentWithSuspense/index.jsx' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/components/atoms/ComponentWithSuspense'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/components/atoms/HtmlContent/index' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/components/atoms/HtmlContent'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/components/atoms/HtmlContent/index.jsx' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/components/atoms/HtmlContent'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/components/atoms/index' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/components/atoms'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/components/atoms/index.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/components/atoms'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/components/index' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/components'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/components/index.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/components'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/components/organisms/__tests__/index.test.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/components/organisms/__tests__/index.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/components/organisms/__tests__/Loader.test.jsx' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/components/organisms/__tests__/Loader.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/components/organisms/index' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/components/organisms'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/components/organisms/index.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/components/organisms'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/components/organisms/Loader/index' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/components/organisms/Loader'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/components/organisms/Loader/index.jsx' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/components/organisms/Loader'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/enums/app.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/enums/app'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/enums/index' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/enums'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/enums/index.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/enums'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/enums/redux.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/enums/redux'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/enums/sw.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/enums/sw'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/hooks/__tests__/useApiRequest.test.jsx' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/hooks/__tests__/useApiRequest.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/hooks/__tests__/useBackPress.test.jsx' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/hooks/__tests__/useBackPress.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/hooks/__tests__/useTheme.test.jsx' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/hooks/__tests__/useTheme.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/hooks/index' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/hooks'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/hooks/index.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/hooks'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/hooks/useApiRequest.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/hooks/useApiRequest'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/hooks/useBackPress.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/hooks/useBackPress'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/hooks/useTheme.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/hooks/useTheme'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/index' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/index.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/providers/__tests__/ReduxProvider.test.jsx' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/providers/__tests__/ReduxProvider.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/providers/index' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/providers'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/providers/index.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/providers'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/providers/ReduxProvider/index' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/providers/ReduxProvider'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/providers/ReduxProvider/index.jsx' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/providers/ReduxProvider'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/redux/index' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/redux'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/redux/index.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/redux'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/redux/queries/__tests__/baseQueryFn.test.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/redux/queries/__tests__/baseQueryFn.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/redux/queries/baseQueryFn.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/redux/queries/baseQueryFn'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/redux/queries/index' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/redux/queries'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/redux/queries/index.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/redux/queries'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/redux/slices/__tests__/apisSlice.test.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/redux/slices/__tests__/apisSlice.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/redux/slices/__tests__/appSlice.test.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/redux/slices/__tests__/appSlice.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/redux/slices/__tests__/navigationSlice.test.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/redux/slices/__tests__/navigationSlice.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/redux/slices/apisSlice.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/redux/slices/apisSlice'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/redux/slices/appSlice.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/redux/slices/appSlice'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/redux/slices/index' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/redux/slices'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/redux/slices/index.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/redux/slices'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/redux/slices/navigationSlice.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/redux/slices/navigationSlice'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/services/__tests__/SWRegistration.test.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/services/__tests__/SWRegistration.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/services/index' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/services'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/services/index.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/services'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/services/SWRegistration.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/services/SWRegistration'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/stories/__tests__/Colors.test.jsx' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/stories/__tests__/Colors.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/stories/__tests__/Icons.test.jsx' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/stories/__tests__/Icons.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/stories/__tests__/Typography.test.jsx' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/stories/__tests__/Typography.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/stories/Colors/index' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/stories/Colors'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/stories/Colors/index.jsx' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/stories/Colors'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/stories/Colors/index.stories.jsx' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/stories/Colors/index.stories'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/stories/Icons/index' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/stories/Icons'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/stories/Icons/index.jsx' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/stories/Icons'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/stories/Icons/index.stories.jsx' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/stories/Icons/index.stories'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/stories/Typography/index' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/stories/Typography'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/stories/Typography/index.jsx' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/stories/Typography'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/stories/Typography/index.stories.jsx' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/stories/Typography/index.stories'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/apiUtils.test.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/__tests__/apiUtils.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/appUtils.test.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/__tests__/appUtils.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/arrayUtils.test.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/__tests__/arrayUtils.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/beforeUnload.test.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/__tests__/beforeUnload.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/classNames.test.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/__tests__/classNames.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/commonUtils.test.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/__tests__/commonUtils.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/converters.test.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/__tests__/converters.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/cookieUtils.test.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/__tests__/cookieUtils.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/deviceUtils.test.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/__tests__/deviceUtils.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/load.test.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/__tests__/load.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/logsUtils.test.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/__tests__/logsUtils.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/objectUtils.test.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/__tests__/objectUtils.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/preferredColorScheme.test.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/__tests__/preferredColorScheme.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/queryUtils.test.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/__tests__/queryUtils.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/reactUtils.test.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/__tests__/reactUtils.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/reportWebVitals.test.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/__tests__/reportWebVitals.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/__tests__/stringUtils.test.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/__tests__/stringUtils.test'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/apiUtils.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/apiUtils'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/appUtils.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/appUtils'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/arrayUtils.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/arrayUtils'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/classNames.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/classNames'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/commonUtils.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/commonUtils'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/converters.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/converters'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/cookieUtils.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/cookieUtils'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/deviceUtils.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/deviceUtils'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/eventListeners/beforeUnload.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/eventListeners/beforeUnload'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/eventListeners/index' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/eventListeners'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/eventListeners/index.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/eventListeners'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/eventListeners/load.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/eventListeners/load'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/eventListeners/preferredColorScheme.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/eventListeners/preferredColorScheme'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/index' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/index.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/logsUtils.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/logsUtils'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/objectUtils.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/objectUtils'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/queryUtils.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/queryUtils'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/reactUtils.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/reactUtils'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/reportWebVitals.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/reportWebVitals'>;
}
declare module '@arpitmalik832/react-js-rollup-library/src/utils/stringUtils.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/src/utils/stringUtils'>;
}
declare module '@arpitmalik832/react-js-rollup-library/style-dictionary.config.js' {
  declare module.exports: $Exports<'@arpitmalik832/react-js-rollup-library/style-dictionary.config'>;
}
