// flow-typed signature: 9b6496571fc6175511a634fce2a0c995
// flow-typed version: <<STUB>>/@svgr/rollup_v^8.1.0/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@svgr/rollup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@svgr/rollup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@svgr/rollup/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@svgr/rollup/dist/index' {
  declare module.exports: $Exports<'@svgr/rollup/dist'>;
}
declare module '@svgr/rollup/dist/index.js' {
  declare module.exports: $Exports<'@svgr/rollup/dist'>;
}
